# Generated by Django 5.2.4 on 2025-07-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(upload_to='media/projects_thumbnails/')),
                ('link_github', models.URLField(blank=True)),
                ('link_live', models.URLField(blank=True)),
            ],
        ),
    ]
