# Generated by Django 5.2.4 on 2025-07-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to='projects_thumbnails/'),
        ),
    ]
